# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'
 source 'https://github.com/CocoaPods/Specs.git'

target 'JKAutoReleaseObject' do
  
  pod 'JKAutoReleaseObject', '~> 1.0.0'

end
